name: 游냍 Reporte de Bug
description: Reporta un error o problema
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug! 
  
  - type: textarea
    id: descripcion
    attributes:
      label: Descripci칩n del bug
      description: 쯈u칠 est치 pasando?
      placeholder: "Cuando intento..."
    validations:
      required: true
      
  - type: dropdown
    id: componente
    attributes:
      label: 쮻칩nde ocurre?
      options:
        - Dashboard
        - Categorizaci칩n
        - Scraping de emails
        - Otro
    validations:
      required: true